version: '3.9'
volumes:
  projeto_postgres:
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/home/app/api
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    build: postgres
    image: projeto_postgres-13-alpine-multi-user
    volumes:
      - projeto_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env